<a href="https://colab.research.google.com/github/valentina2095/MLCourse/blob/master/1_Lineal_Algebra_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Question 1.

* Print the sum of matrixes A and B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [3]:
# Answer 1.
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([[6, 5],
              [4, 3],
              [2, 1]])

print(A + B)


[[7 7]
 [7 7]
 [7 7]]


# Question 2

* Print the sum of matrix + scalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [4]:
# Answer 2.
M = np.array([[6, 3],
              [9, 5],
              [4, 8]])

N = 2.5

print(M + N)


[[ 8.5  5.5]
 [11.5  7.5]
 [ 6.5 10.5]]


# Question 3.

* Print the transposed matrix of  $J$  -->  $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [5]:
# Answer 3.
J = np.array([[9, 2, 3],
              [3, 7, 4],
              [5, 6, 9]])

print(J.T)


[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Question 4.

* For the $ J ^ t $ matrix, calculate your transpose to obtain the original matrix J. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [6]:
# Answer 4.
print(J.T.T)


[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Question 5.

* 
What are the missing values? 

$$
\left(\begin{array}{cc} 
? & 1\\
0 & 0
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * so that the answer is like this:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

*  Print the result and the answer.

In [12]:
# Answer 5.
miss_1, miss_2 = 0, 0
m1 = np.array([[miss_1, 1],
               [0,      0],])

m2 = np.array([[1,      0],
               [1, miss_2],])

np.dot(m1, m2)


array([[1, 0],
       [0, 0]])

# Question 6.
* ¿ What is the dot product matrixes  $L$ y $K$ = : ?

$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [13]:
# Answer 6.
L = np.array([[3, 5],
              [7, 1]])

K = np.array([[3, 12],
              [6, 4]])

np.dot(L, K)

array([[39, 56],
       [27, 88]])

# Question 7.

* ¿ What is the determinant of the following matrix  ? (Print the answer)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [14]:
# Answer 7.
M = np.array([[1, 2, 0],
              [1, 2, 0],
              [0, 1, 1]])

np.linalg.det(M)

0.0

# Question 8.

* ¿ What is the determinant of the following matrix ? (Print the answer)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [15]:
# Answer 8.
M = np.array([[0, 1, 1],
              [1, 0, 0],
              [0, 0, 1]])

np.linalg.det(M)

-1.0

# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
0 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [18]:
miss = 2
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x = np.array([0, miss, 0])

np.dot(M, x)

array([ 4, 10, 16])